// <auto-generated />
namespace Probe.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class DataMigrationv12 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DataMigrationv12));
        
        string IMigrationMetadata.Id
        {
            get { return "201503282351322_DataMigrationv1.2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
